# Generated by Django 4.2.1 on 2023-09-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0008_userdetail_u_otp'),
        ('cart', '0006_alter_order_ordered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('INR', 'Indian Rupee')], default='INR', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('refund', 'Refund')], default='refund', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_store.userdetail')),
            ],
        ),
    ]
